CREATE SCHEMA IF NOT EXISTS haproxy;

CREATE TABLE haproxy.stats
(
	"pxname" text,
	"svname" text,
	"qcur" integer,
	"qmax" integer,
	"scur" integer,
	"smax" integer,
	"slim" integer,
	"stot" integer,
	"bin" integer,
	"bout" integer,
	"dreq" integer,
	"dresp" integer,
	"ereq" integer,
	"econ" integer,
	"eresp" integer,
	"wretr" integer,
	"wredis" integer,
	"status" integer,
	"weight" integer,
	"act" integer,
	"bck" integer,
	"chkfail" integer,
	"chkdown" integer,
	"lastchg" integer,
	"downtime" integer,
	"qlimit" integer,
	"pid" integer,
	"iid" integer,
	"sid" integer,
	"throttle" integer,
	"lbtot" integer,
	"tracked" integer,
	"type" integer,
	"rate" integer,
	"rate_lim" integer,
	"rate_max" integer,
	"check_status" integer,
	"check_code" integer,
	"check_duration" integer,
	"hrsp_1xx" integer,
	"hrsp_2xx" integer,
	"hrsp_3xx" integer,
	"hrsp_4xx" integer,
	"hrsp_5xx" integer,
	"hrsp_other" integer,
	"hanafail" integer,
	"req_rate" integer,
	"req_rate_max" integer,
	"req_tot" integer,
	"cli_abrt" integer,
	"srv_abrt" integer,
	"comp_in" integer,
	"comp_out" integer,
	"comp_byp" integer,
	"comp_rsp" integer,
	"lastsess" integer,
	"last_chk" integer,
	"last_agt" integer,
	"qtime" integer,
	"ctime" integer,
	"rtime" integer,
	"ttime" integer,
	"recorded_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

